[workspace]
members = [
    "mozzart-std",
    "mozzart-app",
    "mazzart-ply"
]

resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = []
description = "Mozzart workspace"
license = "MIT" 